
skillMetadata:
  sections:
    - name: API Key
      fields:
        - type: label
          label: The Air Quality skill requires an API key. Click <a href='https://aqicn.org/data-platform/token/#/'>here</a> to request a token from the <a href='https://waqi.info/'>World Air Quality Project</a>.
        - name: APIKey
          type: text
          label: Enter API key
          value: ""
          placeholder: demo
